vexim/vexim2

vexim/adminuserchange.php

When editing an existing mailaccount with further aliases, they don't show up because of an false sql-query.

Admin-Account doesn’t show Aliases for accounts. SQL query corrected

---

docs/configure

Today, the use of the submission port or SSL port can be activated right away.

Add submission port 587 and SSL for incoming SMTP connections.

---

vexim/adminaliasadd.php
vexim/adminaliasaddsubmit.php
vexim/adminaliaschange.php
vexim/adminaliaschangesubmit.php
vexim/userchange.php

We introduced the spam_drop-function that allowed the direct deletion of spam mails (instead of moving it to a special spam-directory. We didn't add this feature for alias-addresses (mail forwarding), all mails were forwarded. With this feature you can decide if a spam mail beyond the sa-refuse-tag is either deleted or forwarded.
Forwarded spam-mails can lead to a bad reputation of a mail server.

add spam_drop for alias-address

---

vexim/config/header.php
vexim/config/variables.php.example
vexim/siteaddsubmit.php

We will also not substitute paths with the result of `realpath()` anymore, and will not accept paths not starting with a `/` character.
The check for actual existing of the directory may be disabled in settings, if that is necessary.

Fail if domain mail directory does not exist when creating a new domain. Fixes #71.

---

docs/configure
docs/debian-conf.d/router/250_vexim_virtual_domains
docs/debian-conf.d/transport/30_vexim_virtual_delivery

fixes: https://github.com/vexim/vexim2/issues/81
Works on debian jessie. Compatible with exim 4.82 (ubuntu 14.04)

fix headers_remove in the transport section for exim >4.82. Fixes #81

---

vexim/config/Tests/functionsValidatePasswordTest.php
vexim/config/functions.php

The latest update https://github.com/vexim/vexim2/commit/d06625b80abc6378cb4aa41c8fdbcaec03ce0d82 introduced a bug into the validate_password() function as it returns true for null values. 
E.g.: **siteaddsubmit.php** line **82**
**if (validate_password($_POST['clear'], $_POST['vclear']))** returns *true* if *clear* and *vclear* input fields have been removed from the DOM before submitting.
The patch also includes tests for the function and some small changes to the function and documentation.

Adding empty-password users through a bug in validate_password()

---

vexim/adminuserchangesubmit.php
vexim/userchangesubmit.php

Repaired the max-massage-size problems discovered during tests of https://github.com/vexim/vexim2/pull/100#issuecomment-166034354.
When an adminuser changed the message size for a user, the `maxmsgsize` was ignored. I added a control.
A further issue was discovered for users changing their settings (userchangesubmit), the `maxmsgsize` was working for a domain with limited massage size (`maxmsgsize>0`) but when the limit was 0 (unlimited), the user could set an individual limit.

Maximum messages size parameter was ignored for adminuserchange.

---

docs/configure
docs/debian-conf.d/router/250_vexim_virtual_domains
vexim/admingroupchange.php

If you are using a user table where the username of each user is not their e-mail address (for example #106), groups won't work because provided exim configuration resolves group addresses to the usernames of their members, instead of their e-mail addresses. This works when their usernames are their e-mail addresses, but will fail otherwise.
This patch also fixes forms that assume that username = e-mail address to correctly show e-mail addresses.

Fix groups receipts

---

vexim/adminuserdelete.php

After an account is deleted and the redirection-header() is set, there is no point to continue to run the script which show the confirmation message.

Add die()-argument

---

vexim/adminaliaschangesubmit.php

`adminaliaschangesubmit.php` needs the changes made here https://github.com/vexim/vexim2/commit/df0bfcac678713f009c909aa37d9515f91f08276 as well.

Can't specify sa-settings when SA is disabled for domain.

---

vexim/login.php

`userenabled` is not queried in https://github.com/vexim/vexim2/blob/master/vexim/login.php#L17 so `$row[userenabled]` doesn't exist. We could add this to the SQL queries but it why should someone disable siteadmin? Via vexim, there is no way to do (or undo) this.

Always allow siteadmin to login

---

docs/configure
docs/debian-conf.d/main/00_vexim_listmacrosdefs
docs/debian-conf.d/router/250_vexim_virtual_domains

Two 'headers_remove' options cause error in exim 4.80 from Debian Wheezy.

Remove both spam headers in single 'headers_remove' in virtual_domains router.

---

vexim/admincatchallsubmit.php
vexim/userchange.php
vexim/userchangesubmit.php

Some smaller fixes:
* New catchall, we used `$_POST[user_id]` even though this does not exist
* userchange: when only the `realname` is changed in the upper form, the script runs the other updates and creates errors on non existing `$_POST[value]`-variables.
* userchange: option to `store forwarded mail locally` makes only sense when forwarding is active.

Smaller fixes on new catchall and userchange

---

vexim/adminuserchange.php

Some minor changes to `adminuserchange`:
* same position of submit buttons
* Show header `Aliases for this account` only if there are aliases

Harmonize submit buttons, show aliases only if used

---

setup/create_db.pl
setup/mysql.sql
setup/pgsql.sql

New limits are:
- Filesystem paths: 4096 characters (current default limit of the Linux kernel)
- Domain names: 255 characters. Practical limit is in fact 252, but nevermind
- Localparts: 64 characters (per RFC3696, Errata #1690)

Updated some field lengths. Fixes #108.

---

docs/configure
docs/debian-conf.d/router/249_vexim_ditch_routers
docs/debian-conf.d/router/250_vexim_virtual_domains

Only respect the sa/av-settings of a user if it was enabled for the domain.

Respect domain-wide settings for spamassassin and avscan

---

README.md

Access to SpamAssassin mail scanning functionalities is currently integrated using Exim's internal method (exiscan and 'spam' clauses). Installing and enabling sa-exim would duplicate message processing and conflict with suggested Debian configurations.
Fixes #131.

Removed reference to sa-exim Debian package

---

docs/vexim-acl-check-content.conf

Re-enable by default the 'accept' ACL clause which skips spam-detection scanning via SpamAssassin for large messages (300 KB). Email scan in this case has a considerable risk to be wastefully killed by scanning timeout, since processing time grows exponentially w.r.t. size, and very little probability of being successful, since most of spam is under 10 KB.
The setting was disabled in commit f8c2c6dc7f982e5d2142586d38c1d6c002f2f2d0 and merged in pull request #24, where a thorough discussion on the subject can be found.

Bring back message limit for calls to SpamAssassin

---

vexim/siteadd.php

If you add an alias domain, you have to choose from a list of existing domains. This list was unsorted (or by domain_id). It's better to have a alphabetical list.

sort alias-destination alphabetically

---

vexim/adminuseraddsubmit.php
vexim/config/header.php

If you forget to set a `realname` for a new account, its creation will fail. I think this is a bad behavior because this setting is not critical to have a working configuration and furthermore, you can easily add a realname later. To avoid an empty value, the `realname` is set to the `localpart` of the new mail account.

Set empty realname to localpart

---

docs/configure

Just applying the suggestion of @SvenBunge: https://github.com/vexim/vexim2/pull/45#issuecomment-130092012
It worked for me on Debian 7/8 and Ubuntu 14.04.

TLS cipher settings

---

docs/configure
docs/vexim-acl-check-rcpt.conf

Only accept mail from servers with correct reverse DNS settings.
A correct rDNS is required as major mail servers reject mails from servers without one (e.g. gmail).

Add reverse lookup

---

setup/mysql.sql

- All id columns have been changed to int(10) unsigned not null
- Foreign keys have been added to all tables referencing other tables
- Default `uid` and `gid` values in `domains` table have been changed to `65534`. This alleviates the need to edit this file manually before applying it. From looking at the code, it seems to me that `uid` and `gid` are always passed when creating a domain, so this requirement to edit the SQL default value is most likely unnecessary.
The SQL file itself was created using `mysqldump` and edited manually afterwards, that's why most of the file differs: `mysqldump` adds backticks around fields and indents them differently from what we had.
All FK's are currently ON UPDATE CASCADE ON DELETE CASCADE. This might need some tuning, although I'm not exactly sure. …

Updated MySQL setup script

---

docs/configure

Tested on debian 8 👍 
Follow up on changes in https://github.com/vexim/vexim2/pull/170

Remove user/group assignment and transports for alias-forwards.

---

setup/pgsql.sql

This updates the PostgreSQL setup script to match the MySQL one. I've tested and it works, or at least is successfully being executed with `psql`.
I haven't added the random siteadmin password feature though: the `CRYPT()` function in PostgreSQL [supports only a small number of hashing methods](https://www.postgresql.org/docs/9.5/static/pgcrypto.html#AEN172965), of which only MD5 is universally supported. I tried passing an SHA-512 salt to `CRYPT()`, but it falls back to the DES algorithm in that case. Bcrypt is supported, but it's not supported by Linux, so it's not exactly an option.
I figured out it's better to set the password to our traditionally used 'CHANGE' in this case, with hopes that the siteadmin will change it.

Synchronized PostgreSQL setup script with the MySQL script

---

vexim/index.php

This should prevent Vexim installations from appearing in Google and other search results. They should really be private.

Added a robots exclusion meta tag to index.php

---

vexim/adminuserchange.php
vexim/adminuserchangesubmit.php
vexim/config/functions.php
vexim/userchange.php
vexim/userchangesubmit.php

Instead of using these functions provided by the IMAP module, which might be unavailable, we can use `quoted_printable_encode()` and `quoted_printable_decode()`. This means that we'll only depend on the IMAP module to check user's quota from now on.

Replace `imap_qprint()` and `imap_8bit()` with `quoted_printable_[de|en]code()`

---

vexim/siteaddsubmit.php

Fix for #211
`alias`-domains are inserted in a completely different table, therefore the split. Indeed we only need passwords for a new local domain, and there was a default password set. Now I changed it to verify passwords only for local domains.

No passwordcheck for relay-domains

---

docs/configure
docs/debian-conf.d/main/00_vexim_listmacrosdefs
docs/debian-conf.d/router/249_vexim_ditch_routers
docs/debian-conf.d/router/250_vexim_virtual_domains
docs/vexim-acl-check-content.conf

Instead, persist `$spam_*` variables as `$acl_m_spam_*` (except `$spam_score_int`, which persists by itself), and use these variables to add headers at delivery time.
This will add `X-Spam-Score`, `X-Spam-Score-Int` and `X-Spam-Bar` headers regardless of whether or not the message is spam, but this can be easily changed.
Comments welcome.

Do not add spam headers during ACL phase so we don't have to remove them later

---

docs/configure
docs/debian-conf.d/router/249_vexim_ditch_routers

Consider local-part-suffix addresses during routing of spam mails

---

docs/configure
docs/debian-conf.d/router/249_vexim_ditch_routers
docs/debian-conf.d/router/250_vexim_virtual_domains

`sa_tag` and `sa_refuse` settings should be treated as minimum values to induce the effect, not as maximum values which do NOT induce it.
For example, if I have `sa_tag=20`, I expect all messages with spam score 2.0 or above tagged, as opposed to only messages above 2.0 being tagged.
Fixes #223

Treat SA tag and refuse scores properly

---

vexim/admin.php
vexim/adminalias.php
vexim/adminaliasadd.php
vexim/adminaliaschange.php
vexim/adminaliasdelete.php
vexim/admincatchall.php
vexim/admincatchalladd.php
vexim/adminfail.php
vexim/adminfailadd.php
vexim/adminfailchange.php
vexim/admingroup.php
vexim/admingroupadd.php
vexim/admingroupchange.php
vexim/admingroupdelete.php
vexim/adminlists.php
vexim/adminuser.php
vexim/adminuseradd.php
vexim/adminuserchange.php
vexim/adminuserdelete.php
vexim/index.php
vexim/site.php
vexim/siteadd.php
vexim/sitechange.php
vexim/sitedelete.php
vexim/sitepassword.php
vexim/userchange.php

Put `<!DOCTYPE html>` to each file.
index.php:
- use new `autofocus` option on first field instead of inline-javascript (localpart field doesn't exist anymore https://github.com/vexim/vexim2/pull/110)
- use existing css class instead of inline-css

Add Doctype in each file, clean up index.php

---

docs/configure
docs/debian-conf.d/auth/30_vexim_authenticators

Fixes https://github.com/vexim/vexim2/issues/217
And I added two examples in our wiki on how to authenticate without TLS:
https://github.com/vexim/vexim2/wiki/SMTP-Login-without-TLS

Remove option to login without transport encryption

---

vexim/config/authpostmaster.php
vexim/config/authsite.php
vexim/config/functions.php
vexim/config/header.php
vexim/config/variables.php.example
vexim/login.php
vexim/site.php
vexim/style.css

For your consideration, this branch has the following changes:
Primarily, it (optionally) grants the `siteadmin` user the capability to manage each domain as though they were the domain manager. This is accessed via the domains table at `site.php` using the added "manage" link. Clicking "manage" transfers the `siteadmin` to the `admin.php` page with the powers of a domain manager for the chosen site. When the `siteadmin` returns to a siteadmin page (i.e., a page that includes `authsite.php`, they are "logged out" of the domain and return to being the `siteadmin` user.
Secondarily, it has a few other changes in it:
1. Fixed a warning message when `password_strengthcheck` is called with no `username` in `$_POST`, e.g. from `adminuseradd.php`.
2. Added some zebra striping to the domains …

Give siteadmin user the ability to manage domains as a domain manager

---

docs/configure
docs/vexim-acl-check-content.conf

I always run my spamassassin with the `vexim` user. This way all the .spamassassin training files, special configuration, ... is within the home-folder of the `vexim`-user.
Does it make sense to take the exim-user?

Run spamassassin with vmail user

---

docs/vexim-acl-check-mime.conf

add a $ to regex to not filter filenames including a domainname like used in dmarc reports.
fixes #251

fix regex for filenames including .com domains

---

docs/debian-conf.d/router/250_vexim_virtual_domains

This query returns multiple records when the user is a member of multiple groups therefore email gets rejected. Exim expects a single record here.

Fix errors when the user is a member of multiple groups

---

vexim/adminuseraddsubmit.php

With typo in `domains` table name in SELECT the check for maxaccounts never happens.

Domains table name patch

---

vexim/adminaliasadd.php
vexim/adminaliasdelete.php
vexim/adminfail.php
vexim/adminfailadd.php
vexim/adminfailchange.php
vexim/admingroupchange.php
vexim/admingroupdelete.php
vexim/adminuser.php
vexim/adminuserchange.php
vexim/siteadd.php
vexim/sitechange.php
vexim/sitedelete.php
vexim/userchange.php

Use `htmlspecialchars()` to escape user-provided vars before output

---

docs/configure

If you have a typo in the mail address or some other fail reason, you get a lot of mails. By default, exim uses 4 days, it was changed to 14 days by this commit: https://github.com/vexim/vexim2/commit/1a826792d86ee2c806464d6c697f70fe6a5fef85
4 days seems more reasonable for a system that is supposed to be connected all the time, it should be enough to cover most temporary problems. Not sure if that was changed by accident?

Revert max retry time to 4 days
