vexim/vexim2

vexim/config/functions.php

Some inspiration from https://github.com/Exim4U/src/blob/master/home/exim4u/public_html/exim4u/config/functions.php

Salt generation: Replace uniqid() with a more secure function from the openssl-library.

---

docs/configure

Now, it should be a cleaner request. Put same spam-routes and -transports into single config-file.

update single exim single config file

---

vexim/sitechangesubmit.php

Fixes bug that reset all settings for all users in domain.

Fix to Disable AV and SA for all users in domain

---

README.md

updated to some recent changes

---

vexim/siteadd.php

Adding the pw-generator to the siteadd-page.

Add PW-generator to siteadd-page

---

vexim/adminaliasaddsubmit.php
vexim/adminaliaschangesubmit.php
vexim/admincatchallsubmit.php
vexim/adminuserchangesubmit.php
vexim/config/header.php
vexim/userchangesubmit.php

In the forms it is said, that the forward address must be a valid e-mail address. Actually this was never checked.

Verify forward e-mail address

---

vexim/adminaliasaddsubmit.php
vexim/adminaliaschangesubmit.php
vexim/adminuserchangesubmit.php
vexim/config/functions.php
vexim/config/header.php
vexim/login.php

Using the !== operator on the password. With hashed passwords, this is no problem, but if clear-passwords are used this could be a problem. ("01"=="1").

Password check operator

---

vexim/config/authsite.php
vexim/config/authuser.php
vexim/config/header.php

Update of db-query in header.php

db-query header.php & syntax

---

vexim/siteaddsubmit.php

fixes https://github.com/vexim/vexim2/issues/87

fix sql statement for relay domain. Fixes#87

---

vexim/adminuser.php
vexim/adminuseraddsubmit.php
vexim/userchangesubmit.php

After some testing, I found:
A global maxmsgsize was not correctly applied.
User couldn't change his preferences (only password). Other little fixes.

apply maxmsgsize as global domain limit and some smaller fixes

---

vexim/adminalias.php
vexim/adminuser.php
vexim/site.php
vexim/style.css

Fixes https://github.com/vexim/vexim2/issues/86

Color disabled accounts/domains red

---

vexim/config/functions.php
vexim/config/header.php
vexim/login.php
vexim/logout.php

Replacing https://github.com/vexim/vexim2/pull/95 to fix https://github.com/vexim/vexim2/issues/88
I put the checks before the session-variable is initialized. Indentation fixes are in a separate commit.

 Deny access to disabled account/domain. Fixes #88

---

vexim/adminaliasaddsubmit.php
vexim/adminfailaddsubmit.php
vexim/admingroupaddsubmit.php
vexim/adminuseraddsubmit.php
vexim/config/functions.php
vexim/config/header.php

Check if mail address is RFC conform.
partly fixes https://github.com/vexim/vexim2/issues/108

Check length of mail address

---

vexim/adminalias.php
vexim/adminaliasadd.php
vexim/adminaliaschange.php
vexim/adminaliasdelete.php
vexim/admincatchall.php
vexim/admincatchalladd.php
vexim/adminfail.php
vexim/adminfailadd.php
vexim/adminfailchange.php
vexim/admingroupadd.php
vexim/admingroupchange.php
vexim/admingroupdelete.php
vexim/adminlists.php
vexim/adminuseradd.php
vexim/adminuserchange.php
vexim/adminuserdelete.php
vexim/site.php
vexim/sitechange.php
vexim/sitepassword.php
vexim/userchange.php

Just a small typo in a few files.

Fix typo for css style Menu

---

vexim/adminaliasaddsubmit.php
vexim/adminfail.php
vexim/adminuserchange.php
vexim/adminuserchangesubmit.php
vexim/config/header.php
vexim/login.php
vexim/siteadd.php
vexim/siteaddsubmit.php
vexim/userchange.php
vexim/userchangesubmit.php

* At some places, I fixed error caused by `$_POST["localpart"]`
* The destination for alias-domains can be selected from a list (instead of typing the destination domain manually). This way, we don't need to check the destination domain for existence.

Fix undef variable, improve domain-alias

---

vexim/sitechange.php
vexim/sitechangesubmit.php

Continue work on #100

---

setup/mysql.sql
setup/pgsql.sql

closes #146 for new db install.

Primary key added, table domainalias

---

vexim/adminaliaschange.php
vexim/adminuserchange.php
vexim/adminuserchangesubmit.php
vexim/userchange.php
vexim/userchangesubmit.php

Fix #154 
There is also a small javascript that activates the input field for forwarding when the checkbox for forwarding is active. The problem is when the checkbox is not checked, all inputs to the textfield are ignored.

Allow forwarding to several destinations

---

docs/vexim-acl-check-rcpt.conf

Update DNSBL list. Thanks @hotstepper13
Edit follow up #127

Remove old DNSBL

---

docs/configure
docs/debian-conf.d/main/00_vexim_listmacrosdefs

add *_environment-fix

---

docs/vexim-acl-check-helo.conf

Fixing https://github.com/vexim/vexim2/issues/138

Fixing issue #138

---

vexim/userchangesubmit.php

**Reproduce**:
* Login as a non-admin user
* Change password, password and confirmation mismatch
**Expected result**
No change of password + Error message
**Actual result**
No change of password + Confirmation that password was changed
@rimas-kudelis

Fix error message when passwords don't match

---

README.md

fixes https://github.com/vexim/vexim2/issues/121
Example taken from the install instruction of the vexim-FreeBSD-port.

user creation on FreeBSD systems fixed.

---

setup/mysql.sql

This is an alternative for #178. With random passwords in place, checks for `$password === 'CHANGE'` would become obsolete.
@Udera, what do you think?

Use random password for siteadmin, output it nicely into terminal

---

vexim/login.php

We removed the default password in https://github.com/vexim/vexim2/pull/181, so we can remove the check for it as well.

Remove check if default password ‘CHANGE’ is used.

---

setup/mysql.sql

This is a small cosmetic change, puts all editable stuff at the top of the file.

MySQL: move DB and user creation above SET statements

---

vexim/adminaliasaddsubmit.php
vexim/adminaliaschangesubmit.php
vexim/adminuseraddsubmit.php
vexim/adminuserchangesubmit.php
vexim/config/functions.php
vexim/config/header.php
vexim/config/variables.php.example
vexim/scripts.js
vexim/siteaddsubmit.php
vexim/sitechangesubmit.php
vexim/sitepasswordsubmit.php
vexim/userchangesubmit.php

closes #134 `check passwort complexity`
this is the server side implementation.
could be improved by using javascript to tell the user if a password is good before submitting it.
additionally i changed the javascript for generating passwords with 12 characters and added more digits to have a higher chance to have a digit in the password.
i'm not a javascript programmer and i don't know how to ensure to have at least one character of each type in the password.

Password strength

---

README.md
docs/configure

Fixes https://github.com/vexim/vexim2/issues/176

Add cipher list for OpenSSL

---

vexim/site.php
vexim/sitechange.php

There were two strings forgotten for translation, and another one was not aligned very well.

fix strings

---

docs/configure
docs/vexim-acl-check-rcpt.conf

Changes:
* accept authenticated senders before checking blacklists
* put everything optional into `vexim-acl-check-rcpt`

Review order of RCPT-ACLs

---

vexim/config/variables.php.example
vexim/index.php
vexim/login.php

enhancement of domainguess feature
solves #135
cut off string given in $domainguess_lefttrim from left side of hostname

Domainguess left trim

---

vexim/config/functions.php
vexim/config/header.php

The $_GET variables are echoed unmodified which represents a XSS risk. 
All the pages that require config/header.php are vulnerable.

Prevent XSS attacks

---

vexim/config/header.php
vexim/config/variables.php.example
vexim/userchangesubmit.php

Remove max_vacation_length, it is long enough since #188

---

docs/configure
docs/vexim-acl-check-content.conf
docs/vexim-acl-check-mime.conf

Fixes https://github.com/vexim/vexim2/issues/232.
@ecki please test.

Remove old demime-function with acl_smtp_mime-settings.

---

docs/configure

These comments referred to some old non-existing files. Updated one reference and removed others.

Remove old outdated comments

---

vexim/admin.php
vexim/adminalias.php
vexim/adminaliasadd.php
vexim/adminaliaschange.php
vexim/adminuseradd.php
vexim/adminuserchange.php
vexim/index.php
vexim/scripts.js
vexim/siteadd.php
vexim/sitepassword.php
vexim/style.css
vexim/userchange.php

To use Content Security Policy properly, we need to remove all inline css/js code. This PR should be merged before this one: https://github.com/vexim/vexim2/pull/235
No functional changes, only moved code.

Remove inline js/css code

---

vexim/config/httpheaders.php
vexim/config/variables.php.example

Add Content Security Policy

---

README.md
docs/clients/courierimap.txt
docs/configure
vexim/admin.php
vexim/adminalias.php
vexim/adminaliasadd.php
vexim/adminaliasaddsubmit.php
vexim/adminaliaschange.php
vexim/adminaliaschangesubmit.php
vexim/adminaliasdelete.php
vexim/admincatchall.php
vexim/admincatchallsubmit.php
vexim/adminfailchange.php
vexim/adminfailchangesubmit.php
vexim/admingroupaddsubmit.php
vexim/admingroupchange.php
vexim/admingroupchangesubmit.php
vexim/admingroupcontentaddsubmit.php
vexim/admingroupcontentdeletesubmit.php
vexim/admingroupdelete.php
vexim/adminuser.php
vexim/adminuseradd.php
vexim/adminuserblocksubmit.php
vexim/adminuserchange.php
vexim/adminuserdelete.php
vexim/config/authuser.php
vexim/sitechangesubmit.php
vexim/sitedelete.php
vexim/sitepasswordsubmit.php
vexim/userchangesubmit.php

Deleted spaces and tabs at EOL

Text formatting

---

vexim/adminuser.php

Fix query for the correct search with LIKE

user search

---

vexim/adminalias.php
vexim/adminuser.php
vexim/sorttable.js

The FreeBSD port (https://www.freshports.org/mail/vexim/) has a patch makes the user tables sortable by mail address instead of mail alias:
https://svnweb.freebsd.org/ports/head/mail/vexim/files/extrapatch-order?revision=435583&view=markup
Having the tables sortable could be very useful, I found this js which allows us to do this, implementation is quite easy: https://kryogenix.org/code/browser/sorttable/

Make tables sortable with js

---

vexim/api/change-user-password.php
vexim/userchangepassword.php

let user change there password over roundcube webmail
roundcube password plugin `plugins/password/config.inc.php`:
```
<?php
$config['password_driver'] = 'httpapi';
$config['password_confirm_current'] = true;
$config['password_minimum_length'] = 8;
$config['password_strength_driver'] = 'pwned';
$config['password_minimum_score'] = 3;
$config['password_algorithm'] = 'sha512-crypt';
$config['password_httpapi_url'] = 'https://veximurl.example.com/userchangepassword.php';
$config['password_httpapi_method'] = 'POST';
$config['password_httpapi_var_user'] = 'user';
$config['password_httpapi_var_curpass'] = 'curpass';
$config['password_httpapi_var_newpass'] = 'newpass';
```

endpoint for user change password
